# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for Steam Grunge Editor — macOS
from pathlib import Path

block_cipher = None

REPO_ROOT  = Path(SPECPATH).parent.parent
ASSETS_DIR = REPO_ROOT / "app" / "assets"

a = Analysis(
    [str(REPO_ROOT / "app" / "main.py")],
    pathex=[str(REPO_ROOT)],
    binaries=[],
    datas=[
        (str(ASSETS_DIR / "brushes"),      "app/assets/brushes"),
        (str(ASSETS_DIR / "fonts"),        "app/assets/fonts"),
        (str(ASSETS_DIR / "templates"),    "app/assets/templates"),
        (str(ASSETS_DIR / "textures"),     "app/assets/textures"),
        (str(ASSETS_DIR / "ratings"),      "app/assets/ratings"),
        (str(ASSETS_DIR / "platformBars"), "app/assets/platformBars"),
        (str(ASSETS_DIR / "icon.png"),     "app/assets"),
        (str(REPO_ROOT  / "requirements.txt"), "."),
    ],
    hiddenimports=[
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtWidgets",
        "PIL",
        "numpy",
        "requests",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="SteamGrungeEditor",
    debug=False,
    strip=False,
    upx=True,
    console=False,          # no terminal window on macOS
    target_arch=None,       # universal2 set in build script for Apple Silicon + Intel
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ASSETS_DIR / "icon.icns"),  # macOS needs .icns (generated by build script)
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="SteamGrungeEditor",
)

# ── macOS .app bundle ─────────────────────────────────────────────────────────
app = BUNDLE(
    coll,
    name="Steam Grunge Editor.app",
    icon=str(ASSETS_DIR / "icon.icns"),
    bundle_identifier="com.huzzama.steamgrungeeditor",
    info_plist={
        "CFBundleName":              "Steam Grunge Editor",
        "CFBundleDisplayName":       "Steam Grunge Editor",
        "CFBundleVersion":           "1.0.0",
        "CFBundleShortVersionString":"1.0.0",
        "CFBundleIdentifier":        "com.huzzama.steamgrungeeditor",
        "CFBundleIconFile":          "icon.icns",
        "NSHighResolutionCapable":   True,
        "NSRequiresAquaSystemAppearance": False,   # supports dark mode
        "LSMinimumSystemVersion":    "11.0",       # macOS Big Sur+
        "CFBundleDocumentTypes": [
            {
                "CFBundleTypeName":       "Image",
                "CFBundleTypeRole":       "Editor",
                "LSItemContentTypes":     ["public.png", "public.jpeg", "public.image"],
            }
        ],
    },
)
